package enums;

public enum Email {
    RECIPIENT,
    PAYMENT_PENDING_RECIPIENT,
    CASH_DIFF_RECIPIENT,
    RECIPIENT_LAST_DATE_DAY,
    CC_RECIPIENT_LAST_DATE_DAY,
    RECIPIENT_PAYMENT_PENDING,
    RECIPIENT_LISTED_POOL,
    RECIPIENT_CASH_DIFFERENCE,
    CC_TBD_PAYMENT_PENDING,
    SOURCING_RECIPIENT,
    CC_SOURCING_RECIPIENT
}
