package constants;

public enum CreditRulesConstant {
    CB_SCORE_BORROWER_HINDU("CB_SCORE_BORROWER_HINDU"),
    CB_SCORE_BORROWER_NON_HINDU("CB_SCORE_BORROWER_NON_HINDU"),
    CB_SCORE_CO_BORROWER_HINDU("CB_SCORE_CO_BORROWER_HINDU"),
    CB_SCORE_CO_BORROWER_NON_HINDU("CB_SCORE_CO_BORROWER_NON_HINDU"),
    WRITE_OFF_BORROWER("WRITE_OFF_BORROWER"),
    WRITE_OFF_CO_BORROWER("WRITE_OFF_CO_BORROWER"),
    THIRTY_PLUS_DPD_TWELEV_MONTH_BORROWER("30+_DPD_TWELEV_MONTH_BORROWER"),
    THIRTY_PLUS_DPD_TWELEV_MONTH_C0_BORROWER("30+_DPD_TWELEV_MONTH_C0_BORROWER"),
    SIXTY_PLUS_DPD_CO_BORROWER("60+_DPD_CO_BORROWER"),
    SIXTY_PLUS_DPD_BORROWER("60+_DPD_BORROWER"),
    NINETY_PLUS_DPD_BORROWER("90+_DPD_BORROWER"),
    NINETY_PLUS_DPD_CO_BORROWER("90+_DPD_CO_BORROWER"),
    CB_ENQUIRIES_COUNT("CB_ENQUIRIES_COUNT"),
    CB_ENQUIRIES_COUNT_CO_BORROWER("CB_ENQUIRIES_COUNT_CO_BORROWER"),
    CHECK_MONTHLY_OBLIGATION_BORROWER("CHECK_MONTHLY_OBLIGATION_BORROWER"),
    CHECK_MONTHLY_OBLIGATION_CO_BORROWER("CHECK_MONTHLY_OBLIGATION_CO_BORROWER"),
    CHECK_DPD_FOR_BOTH("CHECK_DPD_FOR_BOTH"),
    CHECK_DPD_FOR_HISTORY("CHECK_DPD_FOR_HISTORY"),
    CHECK_DPD_FOR_HISTORY_CO_BORROWER("CHECK_DPD_FOR_HISTORY_CO_BORROWER"),
    CURRENT_DPD_BORROWER("CURRENT_DPD_BORROWER"),
    CURRENT_DPD_CO_BORROWER("CURRENT_DPD_CO_BORROWER"),
    OVER_DUE_AMOUNT_CO_BORROWER("OVER_DUE_AMOUNT_CO_BORROWER"),
    OVER_DUE_AMOUNT_BORROWER("OVER_DUE_AMOUNT_BORROWER"),
    CHECK_DPD_OVERDUE_BORROWER("CHECK_DPD_OVERDUE_BORROWER"),
    CHECK_DPD_OVERDUE_CO_BORROWER("CHECK_DPD_OVERDUE_CO_BORROWER"),
    AUTO_LOAN_PERSONAL("Auto Loan (Personal)"),
    AUTO_OVERDRAFT("Auto Overdraft"),
    TWO_WHEELER_LOAN("Two-Wheeler Loan"),
    COMMERCIAL_VEHICLE_LOAN("Commercial Vehicle Loan"),
    COMMERCIAL_EQUIPMENT_LOAN("Commercial Equipment Loan"),
    HOUSING_LOAN("Housing Loan"),
    PROPERTY_LOAN("Property Loan"),
    LOAN_AGAINST_SHARES_SECURITIES("Loan Against Shares / Securities"),
    GOLD_LOAN("Gold Loan"),
    EDUCATION_LOAN("Education Loan"),
    LEASING("Leasing"),
    PERSONAL_LOAN("Personal Loan"),
    CONSUMER_LOAN("Consumer Loan"),
    LOAN_TO_PROFESSIONAL("Loan to Professional"),
    CREDIT_CARD("Credit Card"),
    CHARGE_CARD("Charge Card"),
    FLEET_CARD("Fleet Card"),
    LOAN_AGAINST_CARD("Loan against Card"),
    OVERDRAFT("Overdraft"),
    LOAN_AGAINST_BANK_DEPOSITS("Loan Against Bank Deposits"),
    OD_ON_SAVINGS_ACCOUNT("OD on Savings Account"),
    NON_FUNDED_CREDIT_FACILITY("Non-Funded Credit Facility"),
    BUSINESS_LOAN_GENERAL("Business Loan General"),
    BUSINESS_LOAN_PRIORITY_SECTOR_SMALL_BUSINESS("Business Loan Priority Sector Small Business"),
    BUSINESS_LOAN_PRIORITY_SECTOR_AGRICULTURE("Business Loan Priority Sector Agriculture"),
    BUSINESS_LOAN_PRIORITY_SECTOR_OTHERS("Business Loan Priority Sector Others"),
    BUSINESS_NON_FUNDED_CREDIT_FACILITY_GENERAL("Business Non-Funded Credit Facility General"),
    BUSINESS_NON_FUNDED_CREDIT_FACILITY_PRIORITY_SECTOR_SMALL_BUSINESS("Business Non-Funded Credit Facility-Priority Sector- Small Business"),
    BUSINESS_NON_FUNDED_CREDIT_FACILITY_PRIORITY_SECTOR_AGRICULTURE("Business Non-Funded Credit Facility-Priority Sector-Agriculture"),
    BUSINESS_NON_FUNDED_CREDIT_FACILITY_PRIORITY_SECTOR_OTHERS("Business Non-Funded Credit Facility-Priority Sector-Others"),
    BUSINESS_LOAN_AGAINST_BANK_DEPOSITS("Business Loan Against Bank Deposits"),
    OTHER("Other"),
    TELCO_WIRELESS("Telco Wireless"),
    TELCO_BROADBAND("Telco Broadband"),
    TELCO_LANDLINE("Telco Landline"),
    MICROFINANCE_BUSINESS_LOAN("Microfinance Business Loan"),
    MICROFINANCE_PERSONAL_LOAN("Microfinance Personal Loan"),
    MICROFINANCE_HOUSING_LOAN("Microfinance Housing Loan"),
    MICROFINANCE_OTHERS("Microfinance Others"),
    USED_CAR_LOAN("Used Car Loan"),
    CONSTRUCTION_EQUIPMENT_LOAN("Construction Equipment Loan"),
    USED_TRACTOR_LOAN("Used Tractor Loan"),
    TRACTOR_LOAN("Tractor Loan"),
    P2P_PERSONAL_LOAN("P2P Personal Loan"),
    P2P_AUTO_LOAN("P2P Auto Loan"),
    P2P_EDUCATION_LOAN("P2P Education Loan"),
    STAFF_LOAN("Staff Loan"),
    SECURED_CREDIT_CARD("Secured Credit Card"),
    CORPORATE_CREDIT_CARD("Corporate Credit Card"),
    KISAN_CREDIT_CARD("Kisan Credit Card"),
    LOAN_ON_CREDIT_CARD("Loan on Credit Card"),
    PRIME_MINISTER_JANA_DHAN_YOJANA_OVERDRAFT("Prime Minister Jana Dhan Yojana - Overdraft"),
    MUDRA_LOANS_SHISHU_KISHOR_TARUN("Mudra Loans – Shishu / Kishor / Tarun"),
    BUSINESS_LOAN_SECURED("Business Loan - Secured"),
    BUSINESS_LOAN_UNSECURED("Business Loan Unsecured"),
    PRADHAN_MANTRI_AWAS_YOJANA_CLSS("Pradhan Mantri Awas Yojana - CLSS"),
    GECL_LOAN_SECURED("GECL Loan Secured"),
    GECL_LOAN_UNSECURED("GECL Loan Unsecured"),
    JLG_GROUP("JLG Group"),
    JLG_INDIVIDUAL("JLG Individual"),
    INDIVIDUAL("Individual"),
    SHG_GROUP("SHG Group"),
    SHG_INDIVIDUAL("SHG Individual"),
    SHG_GROUP_GOVT("SHG Group- Govt"),
    SHG_INTRA_GROUP("SHG Intra- Group"),
    OTHERS("Others");


    private String rule;


    CreditRulesConstant(String rule) {
        this.rule = rule;
    }

    public String rule() {
        return this.rule;
    }

}
